title: Jieli Shen # your name (or website title) here
logo: "/images/self.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  I am a data scientist at Walmart eCommerce focusing on customer science. Previous I worked in bank industry developing quantitative algorithms for fixed income trading.
  <br><br>
  I received my PhD in Statistics from Rutgers University, New Brunswickand and BSc in Statistics from University of Science and Technology of China.
  <br><br>
  <a href="https://www.linkedin.com/in/jieli-shen-phd-cfa-frm-02a96758/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
