---
title: "Investing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

&nbsp;

I have been developing systematic investing strategies for my personal investment account, aiming at beating the S&P 500 benchmark in terms of risk-adjusted return. 

&nbsp;

## Enhanced Dollar-Cost Averaging Strategy

The dollar-cost averaging (DCA) method is widely adopted by investors to invest a constant dollar amount into the investment vehicle at regular basis. The strategy modifies the traditional DCA to account into (therefore, timing) the current market condition in order to deliver higher return and lower average than the traditional DCA approach.

&nbsp;

## Regime Switching ETF Strategy

The strategy determines the boarder market regime using a proprietary algorithm, and invests in different ETFs according based on where the current market is, not only to enhance the long-term return, but also reduce volatility avoiding large losses.

&nbsp;

## AI Stock Selection Strategy

The strategy leverages machine learning models that are trained on hundreds of technical, fundamental and sentiment indicators over thousands of stocks to predict their probabilities of price appreciation in the next one month, and constructs portfolios using the stocks with highest winning odds in combination proprietary screening procedures.

&nbsp;

**Historical Performance**

On the last trading day of each month, I will release the stock list selected on the last trading day of the previous month, and its performance during the current month.

* April 2023
  * Stock list: APG, BWXT, CIVI, EVH, IMAX, IR, PWR, TPH, UNM, X
  * Equally weighted portfolio return: +3.36%
  * SPY return: +1.59%
  
* March 2023
  * Stock list: AMBC, AXON, AXSM, CARS, CECO, FTI, PWR, SILK, TMDX, XPRO
  * Equally weighted portfolio return: -7.20%
  * SPY return: +3.31%
  
* Feburary 2023
  * Stock list: ASO, DHI, EXTR, JBL, OI, SMCI, STNG, TPX, TTC, WNC
  * Equally weighted portfolio return: +9.16%
  * SPY return: -2.51%